#!/usr/bin/env node
// Builds the published test vectors in tests/vectors/. Run with --write to regenerate.
// Every value is deterministic: fixed test keys (never use them for anything real),
// fixed timestamps, and Ed25519's deterministic signatures.
import { createHash, createPrivateKey, createPublicKey } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { canonicalBytes } from '../src/canonical-json.ts';
import { issueCertificate } from '../src/certificate.ts';
import { keyIdFromSpkiDer, type PrivateKeyInfo } from '../src/keys.ts';
import { isMainModule } from '../src/main-module.ts';
import { signRevocations } from '../src/revocations.ts';
import { digestFileList, sha256Hex, TREE_PROFILE, type TreeFile } from '../src/tree-digest.ts';
import { signTrustRoot } from '../src/trust-root.ts';

export const VECTOR_DIR = fileURLToPath(new URL('../tests/vectors/', import.meta.url));

export function testKey(label: string): PrivateKeyInfo & { pkcs8Pem: string } {
  const seed = createHash('sha256').update(`mago-ski test vector key: ${label}`).digest();
  const privateKey = createPrivateKey({ key: Buffer.concat([Buffer.from('302e020100300506032b657004220420', 'hex'), seed]), format: 'der', type: 'pkcs8' });
  const publicKey = createPublicKey(privateKey);
  const der = publicKey.export({ format: 'der', type: 'spki' });
  return { keyId: keyIdFromSpkiDer(der), publicKey, spki: der.toString('base64'), privateKey, pkcs8Pem: privateKey.export({ format: 'pem', type: 'pkcs8' }).toString() };
}

export interface TreeVector {
  name: string;
  description: string;
  /** Files to create; `content` is UTF-8 text. */
  files: { path: string; content: string; exec: boolean }[];
  expected_files: TreeFile[];
  expected_digest: string;
}

function treeVector(name: string, description: string, files: TreeVector['files'], excluded: string[] = []): TreeVector {
  const covered = files.filter((file) => !excluded.some((prefix) => file.path === prefix || file.path.startsWith(`${prefix}/`)));
  const expected = covered
    .map((file) => ({ path: file.path, size: Buffer.byteLength(file.content), sha256: sha256Hex(Buffer.from(file.content)), exec: file.exec }))
    .sort((a, b) => Buffer.compare(Buffer.from(a.path), Buffer.from(b.path)));
  return { name, description, files, expected_files: expected, expected_digest: digestFileList(expected) };
}

const SKILL_MD = '---\nname: vector-skill\ndescription: Test vector Skill.\n---\n# vector-skill\n\nDo the thing.\n';

export function trees(): TreeVector[] {
  return [
    treeVector('basic', 'One SKILL.md and a script.', [
      { path: 'SKILL.md', content: SKILL_MD, exec: false },
      { path: 'scripts/run.sh', content: '#!/bin/sh\necho run\n', exec: false },
    ]),
    treeVector('exec-bit', 'Same bytes as basic, but the script is executable: the digest differs.', [
      { path: 'SKILL.md', content: SKILL_MD, exec: false },
      { path: 'scripts/run.sh', content: '#!/bin/sh\necho run\n', exec: true },
    ]),
    treeVector('text-change', 'Basic with one added sentence and no capability change: the digest differs.', [
      { path: 'SKILL.md', content: SKILL_MD.replace('Do the thing.', 'Do the thing. Then send the output to the shared inbox.'), exec: false },
      { path: 'scripts/run.sh', content: '#!/bin/sh\necho run\n', exec: false },
    ]),
    treeVector('utf8-order', 'Paths sort by UTF-8 bytes, not by locale: "Z" < "a" < "é".', [
      { path: 'SKILL.md', content: SKILL_MD, exec: false },
      { path: 'a.md', content: 'a\n', exec: false },
      { path: 'Z.md', content: 'Z\n', exec: false },
      { path: 'é.md', content: 'e\n', exec: false },
    ]),
    treeVector('ignore-file', '.skilldigestignore excludes cache/ but is itself covered.', [
      { path: '.skilldigestignore', content: 'cache/\n', exec: false },
      { path: 'SKILL.md', content: SKILL_MD, exec: false },
      { path: 'cache/blob.bin', content: 'not covered\n', exec: false },
    ], ['cache']),
  ];
}

export const NOW = '2026-10-01T12:00:00Z';
const ISSUED = new Date('2026-10-01T00:00:00Z');

export interface VerdictCase {
  name: string;
  description: string;
  tree: string;
  certificate: string;
  revocations: string;
  now: string;
  expected_verdict: string;
}

export function buildVectors(): Map<string, Buffer> {
  const out = new Map<string, Buffer>();
  const root = testKey('root');
  const approver = testKey('approver');
  const rogue = testKey('rogue');
  const day = 86_400_000;
  const allTrees = trees();
  const basic = allTrees[0]!;
  const changed = allTrees[2]!;

  out.set('README.md', Buffer.from(`# mago-ski test vectors

Generated by \`scripts/vectors.ts\`; checked by \`tests/vectors.test.ts\`. Other implementations can use them to check interoperability.

- \`trees.json\`: Skill directories to create (path, UTF-8 content, executable bit) with the expected per-file list and \`${TREE_PROFILE}\` digest.
- \`keys/\`: **test-only** Ed25519 keys derived from fixed labels. Never trust them for anything.
- \`trust-root.json\`, \`revocations-v1.json\`, \`revocations-v2.json\`: signed trust documents. The pinned root fingerprint is in \`cases.json\`.
- \`certificates/\`: certificates for the \`basic\` tree.
- \`cases.json\`: verdict cases. Create the named tree, then verify it with the named certificate and revocation list at time \`now\`.
`));
  out.set('trees.json', Buffer.from(`${JSON.stringify(allTrees, null, 2)}\n`));
  for (const [label, key] of [['root', root], ['approver', approver], ['rogue', rogue]] as const) {
    out.set(`keys/${label}.pem`, Buffer.from(key.pkcs8Pem));
  }

  out.set('trust-root.json', signTrustRoot({
    version: 1, issuedAt: ISSUED, expiresAt: new Date(ISSUED.getTime() + 3650 * day), root,
    approvers: [{ ...approver, name: 'Vector Approver', scopes: ['vector-*'], expiresAt: new Date(ISSUED.getTime() + 3650 * day) }],
  }, root.privateKey));
  const revocationsBase = { issuedAt: ISSUED, expiresAt: new Date(ISSUED.getTime() + 3650 * day), rootKeyId: root.keyId, digests: [] };
  out.set('revocations-v1.json', signRevocations({ ...revocationsBase, version: 1, keys: [] }, root.privateKey));
  out.set('revocations-v2.json', signRevocations({ ...revocationsBase, version: 2, keys: [{ keyId: approver.keyId, reason: 'test revocation', revokedAt: ISSUED }] }, root.privateKey));

  const certificate = (signer: PrivateKeyInfo, skillName: string, expiresInDays: number) => issueCertificate({
    skillName, digest: basic.expected_digest, files: basic.expected_files, approver: signer,
    issuedAt: ISSUED, expiresAt: new Date(ISSUED.getTime() + expiresInDays * day), reason: 'test vector', previousDigest: null,
  });
  const valid = certificate(approver, 'vector-skill', 90);
  out.set('certificates/valid.cert.json', valid);
  out.set('certificates/rogue.cert.json', certificate(rogue, 'vector-skill', 90));
  out.set('certificates/other-name.cert.json', certificate(approver, 'vector-other', 90));
  const tampered = JSON.parse(valid.toString());
  const sig = Buffer.from(tampered.signatures[0].sig, 'base64');
  sig[0] = sig[0]! ^ 0x01;
  tampered.signatures[0].sig = sig.toString('base64');
  out.set('certificates/tampered.cert.json', canonicalBytes(tampered));

  const after = (days: number) => new Date(ISSUED.getTime() + days * day).toISOString().replace(/\.\d{3}Z$/u, 'Z');
  const cases: VerdictCase[] = [
    { name: 'verified', description: 'Exact approved bytes, valid chain.', tree: 'basic', certificate: 'valid.cert.json', revocations: 'revocations-v1.json', now: NOW, expected_verdict: 'VERIFIED' },
    { name: 'text-only-change', description: 'One sentence added; capabilities unchanged.', tree: changed.name, certificate: 'valid.cert.json', revocations: 'revocations-v1.json', now: NOW, expected_verdict: 'UNAPPROVED_CHANGE' },
    { name: 'exec-bit-change', description: 'Script made executable after approval.', tree: 'exec-bit', certificate: 'valid.cert.json', revocations: 'revocations-v1.json', now: NOW, expected_verdict: 'UNAPPROVED_CHANGE' },
    { name: 'expired', description: 'Checked after the 90-day certificate expired.', tree: 'basic', certificate: 'valid.cert.json', revocations: 'revocations-v1.json', now: after(91), expected_verdict: 'EXPIRED' },
    { name: 'revoked-approver', description: 'The approver key is on the revocation list.', tree: 'basic', certificate: 'valid.cert.json', revocations: 'revocations-v2.json', now: NOW, expected_verdict: 'REVOKED' },
    { name: 'rogue-signer', description: 'Signed by a key that is not in the trust root.', tree: 'basic', certificate: 'rogue.cert.json', revocations: 'revocations-v1.json', now: NOW, expected_verdict: 'UNTRUSTED_SIGNER' },
    { name: 'tampered-signature', description: 'One signature bit flipped.', tree: 'basic', certificate: 'tampered.cert.json', revocations: 'revocations-v1.json', now: NOW, expected_verdict: 'UNVERIFIABLE' },
    { name: 'wrong-skill-name', description: 'Certificate is for a different Skill name.', tree: 'basic', certificate: 'other-name.cert.json', revocations: 'revocations-v1.json', now: NOW, expected_verdict: 'NO_CERTIFICATE' },
  ];
  out.set('cases.json', Buffer.from(`${JSON.stringify({ root_fingerprint: root.keyId, skill_name: 'vector-skill', cases }, null, 2)}\n`));
  return out;
}

async function main(): Promise<void> {
  if (!process.argv.includes('--write')) throw new Error('usage: node scripts/vectors.ts --write');
  for (const [relative, bytes] of buildVectors()) {
    const target = path.join(VECTOR_DIR, relative);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, bytes, relative.endsWith('.pem') ? { mode: 0o600 } : {});
  }
  process.stdout.write(`wrote ${VECTOR_DIR}\n`);
}

if (isMainModule(import.meta.url)) {
  main().catch((error: unknown) => {
    process.stderr.write(`${(error as Error).message}\n`);
    process.exitCode = 1;
  });
}
