name: test

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        node: ['22.18.0', '24.x']
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: ${{ matrix.node }}
      - name: Install development dependencies
        run: npm ci --ignore-scripts
      - name: Type-check
        run: npm run typecheck
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
