name: test

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
        node: ['22.18.0', '24.x']
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: ${{ matrix.node }}
      - name: Install development dependencies
        run: npm ci --ignore-scripts
      - name: Type-check
        run: npm run typecheck
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
